apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kas.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kas.labels" . | nindent 4 }}
  {{- if .Values.kas.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.kas.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
