dns:
  domain: int0.rosa.devshift.net

regional_cluster:
  enable_bastion: true
  enable_cloudtrail: true
  observability:
    prometheus:
      enabled: true

management_cluster_defaults:
  enable_bastion: true
