FROM registry.access.redhat.com/ubi10/ubi:10.1-1770180700

RUN dnf install -y unzip

WORKDIR /src

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

RUN unzip awscliv2.zip

RUN ./aws/install

RUN which aws

RUN aws --version
