{{- if .Values.grafana.sso.secretArn }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-sso
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-sso
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SSO_CLIENT_ID: "{{ "{{ .client_id }}" }}"
        SSO_CLIENT_SECRET: "{{ "{{ .client_secret }}" }}"
        SSO_AUTH_URL: "{{ "{{ .oidc_url }}" }}/protocol/openid-connect/auth"
        SSO_TOKEN_URL: "{{ "{{ .oidc_url }}" }}/protocol/openid-connect/token"
        SSO_API_URL: "{{ "{{ .oidc_url }}" }}/protocol/openid-connect/userinfo"
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.grafana.sso.secretArn }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.grafana.sso.secretArn }}
        property: client_secret
    - secretKey: oidc_url
      remoteRef:
        key: {{ .Values.grafana.sso.secretArn }}
        property: oidc_url
{{- end }}
