hyperfleet:
  applicationName: hyperfleet-operator

  namespace: argocd

  targetNamespace: hyperfleet

  project: default

  source:
    repoURL: https://github.com/openshift-online/rosa-hyperfleet-api.git
    targetRevision: 406c6e265983611378a1c6db40a4248de7aa6c9a
    path: hyperfleet-operator/charts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  helmValues:
    image:
      repository: quay.io/redhat-user-workloads/rosa-tenant/hyperfleet-operator
      tag: "406c6e265983611378a1c6db40a4248de7aa6c9a"
      pullPolicy: Always

    replicaCount: 2

    serviceAccount:
      create: true
      name: hyperfleet-operator
      annotations: {}

    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

